Osamaarshad - todoapp react, redux
osamaarshad20/todoapp pull request #1
Opened 2020-10-20 08:37 UTC by osamaarshad20

2020-10-28 14:13 UTC, iamalisajid requested changes
Lint the code, use es-6.

2020-10-28 14:13 UTC, iamalisajid commented on fake_apis/database.json
> +}
add eof

2020-10-28 14:13 UTC, iamalisajid commented on fake_apis/server.js
> +const fs = require('fs')
It's ok but it's still a large overhead for the code you can use json holders to do so.

2020-10-28 14:13 UTC, iamalisajid commented on fake_apis/users.json
> +}
eof

2020-10-28 14:13 UTC, iamalisajid commented on src/App.js
> +function App() {
user arrow functions.

2020-10-28 14:13 UTC, iamalisajid commented on src/components/AddForm.js
> +    let [text, setText] = useState("");
why passing empty string here ?

2020-10-28 14:13 UTC, iamalisajid commented on src/components/LoginForm.js
> +    let error_message = '';
you can use a single let with all of them also prefer using camelCase in JS

2020-10-28 14:13 UTC, iamalisajid commented on src/components/Todo.js
> +    const deleteHandler = () =>{
Fix indentation over here.

2020-10-28 14:13 UTC, iamalisajid commented on src/index.css
> +  border: 0 !important;
try not to use !important

2020-10-28 14:13 UTC, iamalisajid commented on src/redux/store.js
> +        axios.get('http://localhost:8000/todos')
Put the URLs in env or const files.

2020-10-28 14:13 UTC, iamalisajid commented on src/redux/store.js
> +            })
Fix indentation of this file too.

2020-10-28 14:13 UTC, iamalisajid commented on src/redux/store.js
> +        axios.put('http://localhost:8000/todos/' + todo.id, {
use string interpolation

2020-10-29 07:05 UTC, osamaarshad20 commented on src/components/AddForm.js
> +    let [text, setText] = useState("");
To initialize text as empty string else it will initialize to null which also doesn't effect anything so I've removed it.

2020-10-29 13:59 UTC, iamalisajid requested changes

2020-10-29 13:59 UTC, iamalisajid commented on src/App.js
> +import React from 'react';
use prettier for linting

2020-10-29 13:59 UTC, iamalisajid commented on src/components/AddForm.js
> +    function addHandler(e) {
es6 syntax

2020-10-29 13:59 UTC, iamalisajid commented on src/components/Todo.js
> +
Add props validation

2020-10-29 13:59 UTC, iamalisajid commented on src/components/LoginForm.js
> +    let error_message, email, password = '';
use initial state

2020-10-29 13:59 UTC, iamalisajid commented on src/components/PageHeader.js
> +function PageHeader() {
update value accordingly

2020-10-29 13:59 UTC, iamalisajid commented on src/redux/reducer.js
> +var initial_state = {
use let

2020-10-29 13:59 UTC, iamalisajid commented on src/redux/reducer.js
> +export default function reducer(state = initial_state, action) {
`INITIAL_STATE`

2020-10-29 13:59 UTC, iamalisajid commented on src/redux/urls.js
> +export const LOGIN = 'http://localhost:8000/auth/login';
base_url

2020-11-02 10:39 UTC, iamalisajid requested changes
Still alot of functions with old syntax use es6 or above only.

2020-11-03 23:25 UTC, iamalisajid requested changes

2020-11-03 23:25 UTC, iamalisajid commented on src/components/Auth/LoginForm.js
>      return;
why an empty return, can't this be better ?

2020-11-03 23:25 UTC, iamalisajid commented on src/components/Todo/Todo.js
> +const Todo = (props) => {
destruct the props like you were doing before.

2020-11-03 23:26 UTC, iamalisajid commented on src/redux/store.js
> +  return function (dispatch) {
still no use of es-6 here

2020-11-03 23:26 UTC, iamalisajid commented on src/redux/store.js
> +        console.log("Unable to fetch todos!");
user console.error

2020-11-03 23:26 UTC, iamalisajid commented on src/redux/store.js
> +  return function (dispatch) {
can't we use es-6 in this file ?

2020-11-03 23:27 UTC, iamalisajid commented
Try to add the PR description also attach video using loom of the whole application.

2020-11-05 15:47 UTC, iamalisajid requested changes
LGTM, look where you can use return in arrow function where not and refactor it.

2020-11-05 15:47 UTC, iamalisajid commented on src/App.js
> +
Remove these empty spaces.

2020-11-05 15:47 UTC, iamalisajid commented on src/App.js
> +  let auth = useSelector((state) => state.authorized);
`prefer-const`

2020-11-05 15:47 UTC, iamalisajid commented on src/components/Todo/TodoPage.js
> +const TodoPage = () => {
this can be refactored and return keyword can be removed.

2020-11-09 08:15 UTC, iamalisajid requested changes
- Refactor all the possible arrow functions you are using like you did in the TodoPage.js
- Use toast instead of alert.

Also contact page has no addition deletion or anything what are the plans for that ?
Or they just missed in the video ?

2020-11-09 08:16 UTC, iamalisajid commented on src/components/Auth/LoginForm.js
>      return;
?

2020-11-09 11:56 UTC, osamaarshad20 commented
we were not planned for addition deletion to contact page. This is suppose to be as it is.

2020-11-09 12:24 UTC, iamalisajid commented
> we were not planned for addition deletion to contact page. This is suppose to be as it is.

I asked for the contact section of the app and I assumed that it's quite understanding that a section is basically a CRUD implementation.

2020-11-09 12:45 UTC, iamalisajid commented
Please take branch from master and start working on contacts crud.

2020-11-09 13:10 UTC, merged